


server:
    ssl:
        enabled: true # false = use http, true = use https (and the certificat)

spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false # Set false for production
    datasource:
        url: jdbc:postgresql://185.220.205.57:5432/default
        username: tora